name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
  
  jobs: 
   runs-on: ubuntu-latest
   needs: job1
   steps:
     - uses: actions/checkout@v1
     - run: echo "world"   
       env:
         GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
